# title of website
title: oxox

# description of website
description: China Electrical Manufacturers Directory

# favicon of website
favicon: "https://github.com/fourus.png?size=40"

# your website url
url: https://oxox.cn

# github profile url
oxox: "https://oxox.cn"

# footer message
footer: © 2021-2021 @oxox.cn

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili

content:
  categories:
    - name: Sensor
      sites:
        - name: chyesic
          description: Wenzhou Yexi Electric Co., Ltd
          url: https://chyesic.com/
        - name: OMCH
          description: Zhejiang Hugong Automation Technology Co.. Ltd
          url: https://omchsmps.com/
        - name: CNTD
          description: CNTD Electric Technology Co., Ltd
          url: http://www.cntd.com/
        - name: Greegoo
          description: Yidu Greegoo Electrical Manufacturer Co., Ltd
          url: http://greegoo.com/
        - name: NQQK
          description: YUEQING NQQK ELECTRIC FACTORY
          url: https://nqqkelc.com/
        - name: asinele
          description: Yueqing Asin Electric & Automation Co., Ltd
          url: http://asinele.com/
        - name: Winston
          description: YUEQING WINSTON ELECTRIC CO.,LTD
          url: http://www.wstele.net/
        - name: Bxuan
          description: Yueqing Bxuan Electric Co., Ltd
          url: https://www.bxuansensor.com/
        - name: YUMO
          description: YUEQING YUMO ELECTRIC CO.,LTD
          url: https://www.yumoelectric.com/
        - name: Trihero
          description: Zhejiang Kane Electric Co.,Ltd
          url: https://www.chnssr.com/sensor.html
    - name: Solid State Relay （SSR）
      sites:
        - name: Aoyi
          description: Shanghai Aoyi Electric Co., Ltd
          url: http://www.aoyidq.com
        - name: Zonzen
          description: Zhejiang Zonzen Electric Co., Ltd
          url: https://www.zonzen.com/solid-state-relay.html
        - name: MGR (HUIMU)
          description: YUEQING MGR ELECTRONICS ELECTRICS CO., LIMITED
          url: https://electronics.huimultd.com/Product/Solid-State-Relay/Electrical-Motor-Controller/
        
